services:
  - type: web
    name: n-m-traffic-system
    env: static
    buildCommand: npm install
    publishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
